# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171120_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cvv',
            field=models.CharField(blank=True, default=None, max_length=5, null=True, verbose_name='CVV'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name='Number'),
        ),
    ]
