# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 16:18
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171122_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='limit',
        ),
        migrations.AddField(
            model_name='wallet',
            name='chosen_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='Chosen Limit'),
        ),
    ]
