# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20171122_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
